<a href="https://colab.research.google.com/github/YNGMunkee/Math311_linear_algebra_projects/blob/main/gram_schmidt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#lets figure out some vector operations!


In [40]:
# create a vector

v = np.array([1,2,3,4])
v


array([1, 2, 3, 4])

In [41]:
# add vecotr to another vector
v+v

array([2, 4, 6, 8])

In [36]:
#scale a vector
v+v

array([[2],
       [4],
       [6],
       [8]])

In [52]:
# norm of a vector
print(np.linalg.norm(v))

# or
print(np.sqrt(v.dot(v)))

5.477225575051661
5.477225575051661


In [48]:
v.size

4

In [49]:
v*v

array([ 1,  4,  9, 16])

In [57]:
# dot products:
print(v.dot(v))

30


In [60]:
# create 4 random vectors
r1 = np.array([0, 3, -3, 0])
r2 = np.array([2, 6,- 2, 2])
r3 = np.array([-2, 1, -3, 0])
r4 = np.array([2, -4, -2, -4])


In [61]:
print("the first rsndom vector is ", r1)

the first rsndom vector is  [ 0  3 -3  0]


# lets process the first vector

In [62]:
# choose r1
# make a temporary vector t1 = r1
t1 = r1
print(t1)

[ 0  3 -3  0]


In [65]:
# normalize t1, and save it as our nice vector u1
n1 = np.sqrt(t1.dot(t1))
print(n1)
# lets form u1
u1 = 1/n1 * t1
print("our first nice vector is u1: ", u1)

4.242640687119285
our first nice vector is u1:  [ 0.          0.70710678 -0.70710678  0.        ]


In [66]:
# sanity check:
# size ov u1 is 1, and it is orthogonal to other nice vectors
print(np.sqrt(u1.dot(u1)))


1.0


# process the secont vector r2

In [67]:
# choose r2
# make a temporary vector t2 = r2 - (r2 . u1) u1
t2 = r2 - r2.dot(u1) * u1
print(t2)

[2. 2. 2. 2.]


In [69]:
# normalize t2 and save it as u2
n2 = np.sqrt(t2.dot(t2))
print(n2)
# lets form u2
u2 = 1/n2 * t2
print("our first nice vector is u2: ", u2)

4.0
our first nice vector is u2:  [0.5 0.5 0.5 0.5]


In [70]:
# sanity check
# size of u2 is 1, and it is orthogonal to other nice vectors
print(np.sqrt(u2.dot(u2)))
print(u1.dot(u2))

1.0
-3.3306690738754696e-16


# process third vector r3

In [71]:
# choose r3
# make a temporary vector t3 = r3 - (r3 . u1) u1 - (r3 . u2)u2
t3 = r3 - r3.dot(u1) * u1 - r3.dot(u2) * u2
print(t3)

[-1.00000000e+00 -4.44089210e-16  1.33226763e-15  1.00000000e+00]


In [78]:
# normalize t3 and save it as u3
n3 = np.sqrt(t3.dot(t3))
print(n3)
# lets form u3
u3 = 1/n3 * t3
print("our first nice vector is u3: ", u3)

1.4142135623730951
our first nice vector is u3:  [-7.07106781e-01 -3.14018492e-16  9.42055475e-16  7.07106781e-01]


In [79]:
# sanity check
# size of u3 is 1, and it is orthogonal to other nice vectors
print(np.sqrt(u3.dot(u3)))
print(u1.dot(u3))

0.9999999999999999
-8.881784197001252e-16


# process 4th vector r4

In [80]:
# choose r4
# make a temporary vector t4 = r4 - (r4 . u1) u1 - (r4 . u2)u2 - (r4 . u3)u3
t4 = r4 - r4.dot(u1) * u1 - r4.dot(u2) * u2 - r4.dot(u3) * u3
print(t4)

[ 1. -1. -1.  1.]


In [81]:
# normalize t4 and save it as u4
n4 = np.sqrt(t4.dot(t4))
print(n4)
# lets form u3
u4 = 1/n4 * t4
print("our first nice vector is u4: ", u4)

2.0000000000000004
our first nice vector is u4:  [ 0.5 -0.5 -0.5  0.5]


In [82]:
# sanity check
# size of u4 is 1, and it is orthogonal to other nice vectors
print(np.sqrt(u4.dot(u4)))
print(u1.dot(u4))

0.9999999999999999
-2.4424906541753444e-15


In [85]:
print("our nice unit vectors are")
print("u1 = ", u1)
print("u2 = ", u2)
print("u3 = ", u3)
print("u4 = ", u4)

our nice unit vectors are
u1 =  [ 0.          0.70710678 -0.70710678  0.        ]
u2 =  [0.5 0.5 0.5 0.5]
u3 =  [-7.07106781e-01 -3.14018492e-16  9.42055475e-16  7.07106781e-01]
u4 =  [ 0.5 -0.5 -0.5  0.5]
